version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: botdb
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  cache:
    image: redis:7-alpine

  bot:
    build: ./bot
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started

  admin:
    build: ./admin
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  jobs:
    build: ./jobs
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started

volumes:
  db_data: {}
