version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started

  admin:
    build:
      context: .
      dockerfile: admin/Dockerfile
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  jobs:
    build:
      context: .
      dockerfile: jobs/Dockerfile
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_started

volumes:
  db_data: {}
